spring:
  application:
    name: vibe-gateway

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  ignored-services: '*'
  routes:
    vibe-auth:
      path: /auth/**
      service-id: vibe-auth
      sensitive-headers: Cookie,Set-Cookie
    vibe-media:
      path: /media/**
      service-id: vibe-media
      sensitive-headers: Cookie,Set-Cookie
    vibe-post:
      path: /post/**
      service-id: vibe-post
      sensitive-headers: Cookie,Set-Cookie
    vibe-graph:
      path: /graph/**
      service-id: vibe-graph
      sensitive-headers: Cookie,Set-Cookie
    vibe-feed:
      path: /feed/**
      service-id: vibe-feed
      sensitive-headers: Cookie,Set-Cookie

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey